<!DOCTYPE html>
<html lang="es"><head>
<script src="dia3_slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="dia3_slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="dia3_slides_files/libs/quarto-html/popper.min.js"></script>
<script src="dia3_slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="dia3_slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="dia3_slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="dia3_slides_files/libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Workshop IEEE 2026">
  <title>Dia 3: Evaluación, Validación e Interpretación</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="dia3_slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="dia3_slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="dia3_slides_files/libs/revealjs/dist/theme/quarto-01d2e12cf9942b18581cf72e9d9855eb.css">
  <link href="dia3_slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="dia3_slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="dia3_slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="dia3_slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <meta name="mermaid-theme" content="neutral">
  <script src="dia3_slides_files/libs/quarto-diagram/mermaid.min.js"></script>
  <script src="dia3_slides_files/libs/quarto-diagram/mermaid-init.js"></script>
  <link href="dia3_slides_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Dia 3: Evaluación, Validación e Interpretación</h1>
  <p class="subtitle">De metrica unica a evidencia confiable</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Workshop IEEE 2026 
</div>
</div>
</div>

</section>
<section id="orden-del-día" class="slide level2">
<h2>Orden del día</h2>
<p>Dia 3: <strong>Evaluacion, Validacion e Interpretacion</strong>.</p>
<p>Objetivo de la sesion:</p>
<ul>
<li>Evaluar que tan bueno es el modelo.</li>
<li>Validar que tan confiable es ese resultado.</li>
<li>Interpretar por que ocurre ese comportamiento.</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mensaje central</strong></p>
</div>
<div class="callout-content">
<p>Un numero en un solo split no es evidencia. Evidencia es un numero que se sostiene bajo variacion de semillas, hiperparametros y umbrales, y que podemos explicar.</p>
</div>
</div>
</div>
</section>
<section id="recordatorio-del-pipeline-dia-2" class="slide level2">
<h2>Recordatorio del pipeline (Dia 2)</h2>
<p>Pipeline existente (no se reemplaza):</p>
<ul>
<li>YAML para decisiones experimentales.</li>
<li>DVC para reproducibilidad y trazabilidad.</li>
<li>W&amp;B para comparar runs.</li>
</ul>
<p>Principio de hoy: <strong>cambiar poco, aprender mucho</strong>.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Lo que ya tenemos:</strong></p>
<pre><code>configs/baseline.yaml   ← unico archivo que cambia
scripts/train.py        ← no se toca
scripts/evaluate.py     ← no se toca
dvc.yaml                ← pipeline intacto</code></pre>
</div><div class="column" style="width:50%;">
<p><strong>Lo que agregamos hoy:</strong></p>
<pre><code>scripts/sweep.py        ← barrido de seeds/params
outputs/errors/         ← analisis de errores
configs/sweep.yaml      ← parametros a variar
models/mlp.py           ← arquitectura a comparar</code></pre>
</div></div>
</section>
<section id="problema-central" class="slide level2">
<h2>Problema central</h2>
<p>Pregunta clave: <strong>¿Podemos confiar en el modelo?</strong></p>
<p>No alcanza con una sola metrica en un solo split.</p>
<p>Necesitamos evidencia en tres ejes:</p>
<ul>
<li><strong>calidad</strong> (<span class="math inline">\(\text{accuracy}, \text{recall}, \text{precision}, \text{F1}, \text{AUC}\)</span>),</li>
<li><strong>estabilidad</strong> (seeds, hiperparametros, threshold),</li>
<li><strong>explicabilidad</strong> (coeficientes vs caja negra).</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Por que tres ejes y no uno?</strong></p>
</div>
<div class="callout-content">
<p>Un modelo puede tener recall = 0.97 en seed 42 y recall = 0.81 en seed 99. El primer numero parece excelente. El segundo revela fragilidad. Sin los tres ejes no sabemos cual de los dos es el resultado real.</p>
</div>
</div>
</div>
</section>
<section id="tres-respuestas-incorrectas-sobre-evaluacion" class="slide level2">
<h2>Tres respuestas incorrectas sobre evaluacion</h2>
<p>Errores clasicos al reportar resultados:</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Respuesta incorrecta 1</strong></p>
</div>
<div class="callout-content">
<p>“Tiene accuracy = 0.96, asi que es excelente.”</p>
<p><em>R2 calculado sobre que datos? Sobre los mismos que usaste para entrenarlo?</em></p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Respuesta incorrecta 2</strong></p>
</div>
<div class="callout-content">
<p>“El recall es 0.97.”</p>
<p><em>Pequeno comparado con que? Importan igual todos los errores? Es estable?</em></p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Respuesta incorrecta 3</strong></p>
</div>
<div class="callout-content">
<p>“Lo probe con algunos casos y funciono bien.”</p>
<p><em>Que significa algunos casos? Como los seleccionaste? Son representativos?</em></p>
</div>
</div>
</div>
<p>La evaluacion correcta responde cuatro preguntas: que metrica, sobre que datos, como interpretar, y como elegir la configuracion.</p>
</section>
<section id="de-la-pregunta-del-dia-1-a-la-evidencia-del-dia-3" class="slide level2">
<h2>De la pregunta del Dia 1 a la evidencia del Dia 3</h2>
<p>La pregunta del Dia 1 fue: <em>recall &gt;= 0.90 y AUC &gt; 0.50?</em></p>
<p>El Dia 2 la respondio con un solo run. Eso no es suficiente.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Lo que reportamos el Dia 2</th>
<th>Lo que preguntamos hoy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>recall = 0.97 con seed 42</td>
<td>recall = 0.97 +/- cuanto con 5 seeds?</td>
</tr>
<tr class="even">
<td>AUC = 0.99 con C = 1.0</td>
<td>AUC cambia si C = 0.01 o C = 100?</td>
</tr>
<tr class="odd">
<td>modelo logistic</td>
<td>logistic sigue siendo mejor que MLP aqui?</td>
</tr>
<tr class="even">
<td>prediccion puntual</td>
<td>que muestras falla sistematicamente?</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>No invalidamos el resultado del Dia 2. Lo ponemos a prueba.</p>
</div>
</div>
</div>
</section>
<section id="evaluacion-mas-alla-de-accuracy" class="slide level2">
<h2>Evaluacion: mas alla de accuracy</h2>
<p>Accuracy puede ocultar errores graves.</p>
<p><span class="math display">\[\text{recall}_{maligno} = \frac{TP}{TP + FN}\]</span></p>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Por que recall y no accuracy?</strong></p>
<p>Supongamos 100 tumores: 37 malignos, 63 benignos.</p>
<p>Un modelo que siempre predice benigno obtiene:</p>
<ul>
<li>accuracy = 63% ← parece razonable</li>
<li>recall maligno = 0% ← no detecta ningun cancer</li>
</ul>
<p>Un falso negativo (cancer no detectado) tiene consecuencias clinicas graves. Un falso positivo (alarma falsa) genera una biopsia adicional — molesto, pero corregible.</p>
</div><div class="column" style="width:45%;">
<p><strong>Las cuatro metricas del dia:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Metrica</th>
<th>Que mide</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>recall</td>
<td>FN que evitamos</td>
</tr>
<tr class="even">
<td>precision</td>
<td>FP que generamos</td>
</tr>
<tr class="odd">
<td>F1</td>
<td>balance recall/precision</td>
</tr>
<tr class="even">
<td>AUC-ROC</td>
<td>capacidad de ranking</td>
</tr>
</tbody>
</table>
<p>La jerarquia es: recall primero, AUC segundo, F1 tercero.</p>
</div></div>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:70%;">
<p><img data-src="https://upload.wikimedia.org/wikipedia/commons/1/17/PPV%2C_NPV%2C_Sensitivity_and_Specificity.svg"></p>
</div><div class="column" style="width:30%;">
<h3 id="qué-muestra-la-figura">¿Qué muestra la figura?</h3>
<ul>
<li>Dos distribuciones:
<ul>
<li><strong>Sano (azul)</strong></li>
<li><strong>Enfermo (rojo)</strong></li>
</ul></li>
<li>Un <strong>threshold (cutoff)</strong> separa clases</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Idea clave</strong></p>
</div>
<div class="callout-content">
<p>Las métricas no son independientes:<br>
<strong>son decisiones sobre errores</strong>.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="por-que-no-existe-una-sola-metrica-correcta" class="slide level2">
<h2>Por que no existe una sola metrica correcta</h2>
<p>La eleccion de metrica es una decision de diseño:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Escenario A — screening clinico:</strong></p>
<p>Errores grandes (cancer no detectado) son cualitativamente peores que errores pequenos.</p>
<p>→ Priorizar recall aunque baje precision.</p>
<p><strong>Escenario B — diagnostico previo a cirugia:</strong></p>
<p>Necesitas alta certeza antes de operar.</p>
<p>→ Priorizar precision aunque baje recall.</p>
</div><div class="column" style="width:50%;">
<p><strong>La pregunta que define la metrica:</strong></p>
<blockquote>
<p><em>De cada 100 mujeres con cancer, cuantas puede perder el sistema antes de que sea inaceptable?</em></p>
</blockquote>
<p>Si la respuesta es “ninguna”: recall es la metrica.</p>
<p>Si la respuesta es “prefiero intervenir solo cuando estoy seguro”: precision es la metrica.</p>
<p>La metrica traduce las consecuencias del error en un numero.</p>
</div></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Regla de diseño experimental</strong></p>
</div>
<div class="callout-content">
<p>(Día 1) La metrica de evaluacion debe elegirse <strong>antes</strong> de entrenar el primer modelo, junto con la pregunta cientifica.</p>
</div>
</div>
</div>
</section>
<section id="la-matriz-de-confusion-resultados-reales" class="slide level2">
<h2>La matriz de confusion — resultados reales</h2>
<div id="cell-confusion-matrix" class="cell" data-fig-height="3.8" data-fig-width="9" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="dia3_slides_files/figure-revealjs/confusion-matrix-output-1.png" id="confusion-matrix" width="974" height="418"></p>
</figure>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Lectura clinica del resultado:</strong></p>
<ul>
<li><strong>41 TP:</strong> malignos correctamente detectados ✓</li>
<li><strong>1 FN:</strong> maligno NO detectado ← el error mas grave</li>
</ul>
</div><div class="column" style="width:45%;">
<div id="test-summary" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>         Metrica Modelo Baseline
        accuracy  0.947    0.632
  recall maligno  0.976    0.000
precision malig.  0.891        —
         AUC-ROC  0.994    0.500

H1_recall_ge_090 : True
H1_auc_gt_050    : True
H1_sustained     : ✓ True</code></pre>
</div>
</div>
</div></div>
</section>
<section id="curva-roc-vs-curva-precision-recall" class="slide level2">
<h2>Curva ROC vs curva Precision-Recall</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Curva ROC</strong></p>
<p>Mide la capacidad de ranking independientemente del threshold.</p>
<ul>
<li>Eje X: tasa de FP (1 - especificidad)</li>
<li>Eje Y: tasa de TP (recall)</li>
<li>AUC = 0.5 → no discrimina (azar)</li>
<li>AUC = 1.0 → separacion perfecta</li>
</ul>
<p>Util para comparar modelos globalmente.</p>
<p><strong>Limitacion:</strong> puede ser optimista con datasets desbalanceados. Un modelo que predice siempre positivo tiene AUC = 0.5, no 0.0.</p>
</div><div class="column" style="width:50%;">
<p><strong>Curva Precision-Recall</strong></p>
<p>Mas informativa con clases desbalanceadas.</p>
<ul>
<li>Eje X: recall (sensibilidad)</li>
<li>Eje Y: precision (valor predictivo positivo)</li>
<li>AP (area bajo PR) mas sensible al desbalance</li>
</ul>
<p><strong>Lectura practica:</strong></p>
<p>Si recall sube de 0.90 a 0.99 pero precision baja de 0.95 a 0.60, estamos generando muchos FP para recuperar pocos FN adicionales.</p>
<p>Esa es la decision clinica: cuanto FP toleramos por cada FN evitado?</p>
</div></div>
</section>
<section class="slide level2">

<div id="cell-roc-pr" class="cell" data-fig-height="3.5" data-fig-width="9" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="dia3_slides_files/figure-revealjs/roc-pr-output-1.png" id="roc-pr" width="1152" height="439"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="validacion-confianza-del-resultado" class="slide level2">
<h2>Validacion: confianza del resultado</h2>
<p>Validar no es repetir exactamente el mismo run.</p>
<p>Se agregan tres pruebas de confianza:</p>
<ul>
<li>multiples seeds,</li>
<li>sensibilidad a hiperparametros,</li>
<li>threshold tuning en validacion.</li>
</ul>
<p>Si pequenas variaciones cambian mucho el recall, el sistema no es robusto.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Regla practica</strong></p>
</div>
<div class="callout-content">
<p>Si <code>std(recall)</code> entre 5 seeds supera 0.03, el resultado reportado en un solo run no es confiable. Hay que reportar media +/- std, no un punto.</p>
</div>
</div>
</div>
</section>
<section id="el-problema-fundamental-del-overfitting" class="slide level2">
<h2>El problema fundamental del overfitting</h2>
<p>Por que las metricas de entrenamiento enganan:</p>
<div class="columns">
<div class="column" style="width:55%;">
<p>Como un estudiante que memoriza las respuestas del examen anterior:</p>
<ul>
<li>En el examen del año pasado: 100/100</li>
<li>En un examen nuevo: 45/100</li>
</ul>
<p>Un modelo puede hacer exactamente lo mismo — memorizar el ruido de los datos de entrenamiento sin aprender la relacion subyacente.</p>
<p><strong>Overfitting:</strong> el modelo ajusta demasiado bien los datos de entrenamiento, incluyendo su ruido. Generaliza mal.</p>
<p><strong>El sweet spot:</strong> visible solo si tenemos datos separados para medir el error de validacion.</p>
</div><div class="column" style="width:45%;">
<p><strong>Error vs complejidad:</strong></p>
<div id="9ca2610c" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="dia3_slides_files/figure-revealjs/cell-6-output-1.png" width="601" height="365"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Error entrenamiento: siempre baja con mas complejidad.</li>
<li>Error validacion: baja hasta el sweet spot, luego sube.</li>
</ul>
<p>El punto de cruce no es visible en los datos de entrenamiento.</p>
</div></div>
</section>
<section id="el-principio-central-de-la-validacion" class="slide level2">
<h2>El principio central de la validacion</h2>
<p><strong>La evaluacion del modelo debe hacerse sobre datos que el modelo nunca vio durante el entrenamiento.</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Train-Test Split:</strong></p>
<pre><code>Dataset completo (n = 569)

split estratificado
├── Training set (80%)
│   └── desarrollo del modelo
└── Test set (20%)
    └── SELLADO hasta el final</code></pre>
<p>Proporciones recomendadas:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Dataset</th>
<th>Train</th>
<th>Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 1K muestras</td>
<td>70%</td>
<td>30%</td>
</tr>
<tr class="even">
<td>1K–10K</td>
<td>80%</td>
<td>20%</td>
</tr>
<tr class="odd">
<td>&gt; 100K</td>
<td>90%</td>
<td>10%</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<p><strong>Por que estratificar?</strong></p>
<p>Sin estratificacion, el test set podria tener por azar 20% de malignos en lugar de 37%.</p>
<p>Las metricas varian enormemente entre corridas sin que el modelo haya cambiado.</p>
<p>Con <code>stratify=y</code>:</p>
<ul>
<li>Train: exactamente 37% malignos</li>
<li>Test: exactamente 37% malignos</li>
</ul>
<p>En sklearn: <code>train_test_split(..., stratify=y)</code></p>
<p>Usar siempre en clasificacion con desbalance.</p>
</div></div>
</section>
<section id="cross-validation-mas-alla-del-split-unico" class="slide level2">
<h2>Cross-validation: mas alla del split unico</h2>
<p>El test set es solo una muestra. Con otra semilla podria ser AUC = 0.78 o AUC = 0.84.</p>
<p>La solucion: no hacer un solo split. Hacer muchos y promediar.</p>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>K-Fold CV (K = 5):</strong></p>
<pre><code>Fold 1: [Val | Tr  | Tr  | Tr  | Tr ]
Fold 2: [Tr  | Val | Tr  | Tr  | Tr ]
Fold 3: [Tr  | Tr  | Val | Tr  | Tr ]
Fold 4: [Tr  | Tr  | Tr  | Val | Tr ]
Fold 5: [Tr  | Tr  | Tr  | Tr  | Val]
         → AUC = mean ± std</code></pre>
<p>Cada observacion aparece exactamente una vez en un fold de validacion.</p>
<p>Ventaja: la desviacion estandar de las K metricas indica que tan estable es el modelo.</p>
</div><div class="column" style="width:45%;">
<p><strong>Que valor de K usar?</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>K</th>
<th>Cuando</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>K = 5</td>
<td>caso general</td>
</tr>
<tr class="even">
<td>K = 10</td>
<td>datasets medianos</td>
</tr>
<tr class="odd">
<td>K = n (LOOCV)</td>
<td>datasets muy pequenos</td>
</tr>
</tbody>
</table>
<p><strong>CV no reemplaza al test set.</strong> Es para desarrollo. El test se evalua una sola vez al final.</p>
</div></div>
</section>
<section id="data-leakage-el-error-mas-costoso" class="slide level2">
<h2>Data leakage: el error mas costoso</h2>
<p>Un modelo que parece excelente en desarrollo y falla en produccion casi siempre tiene data leakage.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Leakage tipo 1 — variables del futuro:</strong></p>
<p>Usamos “numero de materias reprobadas al final del semestre” para predecir abandono.</p>
<p>AUC en desarrollo = 0.95. Al momento de predecir (inicio de semestre), esa variable no existe.</p>
<p><strong>Regla:</strong> cada variable debe estar disponible en el momento en que se hara la prediccion real.</p>
<p><strong>Leakage tipo 2 — preprocesamiento antes del split:</strong></p>
<p>Normalizar con media y desviacion del dataset completo. El escalador “vio” el test set. Las metricas quedan artificialmente buenas.</p>
</div><div class="column" style="width:50%;">
<p><strong>Leakage tipo 3 — el test que ya no es test:</strong></p>
<pre><code>Entrenamos modelo A. AUC test = 0.76
Ajustamos params.   AUC test = 0.79
Cambiamos features. AUC test = 0.82
Reportamos: AUC = 0.82</code></pre>
<p>El test dejo de ser test. Optimizamos sobre el.</p>
<p><strong>El flujo correcto:</strong></p>
<pre><code>1. Split train/test  → Test: SELLADO
2. EDA solo en train
3. Preprocesador en train (fit)
4. K-Fold CV sobre train
5. Seleccionar mejor modelo
6. Evaluar UNA VEZ en test</code></pre>
<p>La regla de oro: todo lo que aprende de los datos debe aprenderse solo de los datos de entrenamiento.</p>
</div></div>
</section>
<section id="validacion-por-multiples-seeds-resultados-reales" class="slide level2">
<h2>Validacion por multiples seeds — resultados reales</h2>
<p><strong>Pregunta:</strong> recall = 0.976 con seed 42 — es representativo o fue suerte?</p>
<div id="cell-seed-sensitivity" class="cell" data-fig-height="3.5" data-fig-width="9" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="dia3_slides_files/figure-revealjs/seed-sensitivity-output-1.png" id="seed-sensitivity" width="1154" height="373"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Lectura de los datos reales</strong></p>
</div>
<div class="callout-content">
<p>Logistic: recall = 0.976 ± 0.000 en los 3 seeds — <strong>varianza cero</strong>, el resultado es completamente estable.</p>
<p>MLP: recall medio 0.968 ± 0.011 — mayor variabilidad, aunque todos los runs superan 0.90.</p>
<p><strong>Conclusion:</strong> Logistic es mas predecible. La estabilidad es un argumento adicional a su favor.</p>
</div>
</div>
</div>
</section>
<section id="threshold-tuning-datos-del-val-set" class="slide level2">
<h2>Threshold tuning — datos del val set</h2>
<p>El threshold de 0.5 no es una ley — es una convencion.</p>
<div id="cell-threshold-tuning" class="cell" data-fig-height="3.5" data-fig-width="9" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="dia3_slides_files/figure-revealjs/threshold-tuning-output-1.png" id="threshold-tuning" width="1154" height="439"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Lectura del resultado real</strong></p>
</div>
<div class="callout-content">
<p>Con t = 0.4: recall = 0.969, precision = 0.969, accuracy = 0.977 — <strong>el punto de mayor F1 y mejor balance</strong>.</p>
<p>Con t = 0.3: recall = 0.969, precision = 0.886 — mismo recall, mas FP (menos precision). No hay ganancia en recall bajando el threshold aqui.</p>
<p>El threshold optimo se elige siempre en <strong>val set</strong>, nunca mirando el test set.</p>
</div>
</div>
</div>
</section>
<section id="experimento-central-logistic-vs-mlp" class="slide level2">
<h2>Experimento central: Logistic vs MLP</h2>
<p>Comparamos dos familias:</p>
<ul>
<li><strong>LogisticRegression</strong> (baseline interpretable),</li>
<li><strong>MLPClassifier</strong> (mayor capacidad, mayor complejidad).</li>
</ul>
<p>Pregunta :</p>
<ul>
<li>El MLP mejora de forma consistente? O solo agrega varianza y opacidad?</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Logistic — lo que ya sabemos:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode numberSource yaml number-lines code-with-copy"><code class="sourceCode yaml"><span id="cb8-1"><a href=""></a><span class="co"># configs/baseline.yaml</span></span>
<span id="cb8-2"><a href=""></a><span class="fu">model</span><span class="kw">:</span></span>
<span id="cb8-3"><a href=""></a><span class="at">  </span><span class="fu">type</span><span class="kw">:</span><span class="at"> logistic_regression</span></span>
<span id="cb8-4"><a href=""></a><span class="at">  </span><span class="fu">class_weight</span><span class="kw">:</span><span class="at"> balanced</span></span>
<span id="cb8-5"><a href=""></a><span class="at">  </span><span class="fu">C</span><span class="kw">:</span><span class="at"> </span><span class="fl">1.0</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Resultado: recall = 0.97 +/- 0.004 (5 seeds)</p>
</div><div class="column" style="width:50%;">
<p><strong>MLP — nuevo experimento:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode numberSource yaml number-lines code-with-copy"><code class="sourceCode yaml"><span id="cb9-1"><a href=""></a><span class="co"># configs/mlp.yaml</span></span>
<span id="cb9-2"><a href=""></a><span class="fu">model</span><span class="kw">:</span></span>
<span id="cb9-3"><a href=""></a><span class="at">  </span><span class="fu">type</span><span class="kw">:</span><span class="at"> mlp</span></span>
<span id="cb9-4"><a href=""></a><span class="at">  </span><span class="fu">hidden_layer_sizes</span><span class="kw">:</span><span class="at"> </span><span class="kw">[</span><span class="dv">64</span><span class="kw">,</span><span class="at"> </span><span class="dv">32</span><span class="kw">]</span></span>
<span id="cb9-5"><a href=""></a><span class="at">  </span><span class="fu">max_iter</span><span class="kw">:</span><span class="at"> </span><span class="dv">500</span></span>
<span id="cb9-6"><a href=""></a><span class="at">  </span><span class="fu">alpha</span><span class="kw">:</span><span class="at"> </span><span class="fl">0.0001</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Se ejecuta con el mismo pipeline, sin cambiar scripts.</p>
</div></div>
</section>
<section id="hiperparametros-que-son-y-por-que-no-se-aprenden-solos" class="slide level2">
<h2>Hiperparametros: que son y por que no se aprenden solos</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Parametros del modelo</strong> — los aprende el algoritmo:</p>
<ul>
<li>En Logistic: los coeficientes <span class="math inline">\(\beta_0, \beta_1, \ldots, \beta_p\)</span></li>
<li>En MLP: los pesos <span class="math inline">\(w\)</span> y sesgos <span class="math inline">\(b\)</span> de cada capa</li>
</ul>
<p>Se obtienen minimizando la funcion de perdida sobre los datos de entrenamiento.</p>
<p><strong>Hiperparametros</strong> — los elige el analista antes de entrenar:</p>
<ul>
<li>En Logistic: <code>C</code> (inverso de regularizacion)</li>
<li>En MLP: numero de capas, neuronas por capa, <code>alpha</code></li>
<li>En cualquier modelo: <code>random_state</code>, <code>max_iter</code></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Por que no aprender C con gradient descent?</strong></p>
<p>Logistic con regularizacion minimiza:</p>
<p><span class="math display">\[\text{MSE} + \frac{1}{C} \sum \beta_j^2\]</span></p>
<p>Si C tambien se aprende minimizando el MSE de entrenamiento, el optimizador siempre elige C = infinito (sin regularizacion) porque eso minimiza el error en train.</p>
<p>El modelo se sobreajustaria completamente.</p>
<p>Para elegir bien los hiperparametros, necesitamos evaluarlos en datos que el modelo no uso para aprenderlos — por eso usamos CV.</p>
</div></div>
</section>
<section id="grid-search-busqueda-exhaustiva" class="slide level2">
<h2>Grid Search: busqueda exhaustiva</h2>
<p>Grid Search define un conjunto finito de valores para cada hiperparametro y prueba todas las combinaciones.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href=""></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> GridSearchCV</span>
<span id="cb10-2"><a href=""></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb10-3"><a href=""></a></span>
<span id="cb10-4"><a href=""></a>param_grid <span class="op">=</span> {</span>
<span id="cb10-5"><a href=""></a>    <span class="st">"C"</span>: [<span class="fl">0.01</span>, <span class="fl">0.1</span>, <span class="fl">1.0</span>, <span class="fl">10.0</span>, <span class="fl">100.0</span>],</span>
<span id="cb10-6"><a href=""></a>    <span class="st">"class_weight"</span>: [<span class="st">"balanced"</span>, <span class="va">None</span>],</span>
<span id="cb10-7"><a href=""></a>}</span>
<span id="cb10-8"><a href=""></a><span class="co"># 5 x 2 = 10 combinaciones x 5 folds = 50 entrenamientos</span></span>
<span id="cb10-9"><a href=""></a></span>
<span id="cb10-10"><a href=""></a>gs <span class="op">=</span> GridSearchCV(</span>
<span id="cb10-11"><a href=""></a>    LogisticRegression(max_iter<span class="op">=</span><span class="dv">500</span>),</span>
<span id="cb10-12"><a href=""></a>    param_grid,</span>
<span id="cb10-13"><a href=""></a>    cv<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb10-14"><a href=""></a>    scoring<span class="op">=</span><span class="st">"recall"</span>,  <span class="co"># metrica primaria</span></span>
<span id="cb10-15"><a href=""></a>    refit<span class="op">=</span><span class="va">True</span>,        <span class="co"># re-entrena con la mejor config sobre todo el train set</span></span>
<span id="cb10-16"><a href=""></a>)</span>
<span id="cb10-17"><a href=""></a>gs.fit(X_train, y_train)</span>
<span id="cb10-18"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Mejor config: </span><span class="sc">{</span>gs<span class="sc">.</span>best_params_<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb10-19"><a href=""></a><span class="bu">print</span>(<span class="ss">f"Recall CV:    </span><span class="sc">{</span>gs<span class="sc">.</span>best_score_<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>La explosion combinatoria</strong></p>
</div>
<div class="callout-content">
<p>Con 10 valores por hiperparámetro y K=5, el número de entrenamientos crece exponencialmente: 50 → 500 → 5,000 → 50,000. Con 3 o más hiperparámetros, Grid Search se vuelve impracticable.</p>
</div>
</div>
</div>
</section>
<section id="random-search-cuando-grid-search-no-escala" class="slide level2">
<h2>Random Search: cuando Grid Search no escala</h2>
<p>En problemas reales con muchos hiperparametros, no todos importan igual. Grid Search gasta recursos explorando variaciones de hiperparametros irrelevantes.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href=""></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> RandomizedSearchCV</span>
<span id="cb11-2"><a href=""></a><span class="im">from</span> scipy.stats <span class="im">import</span> loguniform</span>
<span id="cb11-3"><a href=""></a></span>
<span id="cb11-4"><a href=""></a>param_dist <span class="op">=</span> {</span>
<span id="cb11-5"><a href=""></a>    <span class="st">"C"</span>: loguniform(<span class="fl">0.001</span>, <span class="dv">100</span>),     <span class="co"># muestrea continuamente</span></span>
<span id="cb11-6"><a href=""></a>    <span class="st">"class_weight"</span>: [<span class="st">"balanced"</span>, <span class="va">None</span>],</span>
<span id="cb11-7"><a href=""></a>    <span class="st">"solver"</span>: [<span class="st">"lbfgs"</span>, <span class="st">"saga"</span>],</span>
<span id="cb11-8"><a href=""></a>}</span>
<span id="cb11-9"><a href=""></a><span class="co"># n_iter = presupuesto de evaluaciones</span></span>
<span id="cb11-10"><a href=""></a>rs <span class="op">=</span> RandomizedSearchCV(</span>
<span id="cb11-11"><a href=""></a>    LogisticRegression(max_iter<span class="op">=</span><span class="dv">500</span>),</span>
<span id="cb11-12"><a href=""></a>    param_dist,</span>
<span id="cb11-13"><a href=""></a>    n_iter<span class="op">=</span><span class="dv">30</span>,     <span class="co"># 30 x 5 = 150 entrenamientos vs miles con grid</span></span>
<span id="cb11-14"><a href=""></a>    cv<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb11-15"><a href=""></a>    scoring<span class="op">=</span><span class="st">"recall"</span>,</span>
<span id="cb11-16"><a href=""></a>    random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb11-17"><a href=""></a>)</span>
<span id="cb11-18"><a href=""></a>rs.fit(X_train, y_train)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Flujo recomendado</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Random Search con presupuesto moderado para explorar el espacio. (screening)</li>
<li>Identificar la region prometedora.</li>
<li>Grid Search fino en esa region.</li>
</ol>
<p>Para Logistic con 1-2 hiperparametros: Grid Search es suficiente. Para MLP con 4+ hiperparametros: Random Search primero.</p>
</div>
</div>
</div>
</section>
<section id="resultados-y-trade-offs" class="slide level2">
<h2>Resultados y trade-offs</h2>
<div id="cell-sweep-comparison" class="cell" data-fig-height="4.2" data-fig-width="10" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="dia3_slides_files/figure-revealjs/sweep-comparison-output-1.png" id="sweep-comparison" width="1544" height="634"></p>
</figure>
</div>
</div>
</div>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Resultados del sweep (18 configs totales):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Criterio</th>
<th>Logistic (9)</th>
<th>MLP (9)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>recall medio</td>
<td>0.968</td>
<td>0.968</td>
</tr>
<tr class="even">
<td>recall std</td>
<td>0.012</td>
<td>0.012</td>
</tr>
<tr class="odd">
<td>AUC medio</td>
<td>0.994</td>
<td>0.995</td>
</tr>
<tr class="even">
<td>H1 todos los runs</td>
<td>si</td>
<td>si</td>
</tr>
<tr class="odd">
<td>interpretable</td>
<td>si</td>
<td>no</td>
</tr>
<tr class="even">
<td>tiempo train</td>
<td>&lt; 1 s</td>
<td>~2 s</td>
</tr>
</tbody>
</table>
<p>Ambos modelos sostienen H1. La diferencia en recall es minima.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mensaje clave</strong></p>
</div>
<div class="callout-content">
<p>Los modelos tienen rendimiento <strong>estadisticamente equivalente</strong> en este dataset.</p>
<p>Logistic gana por:</p>
<ul>
<li>Interpretabilidad directa (coeficientes)</li>
<li>Misma estabilidad a menor costo computacional</li>
<li>Explicabilidad regulatoria</li>
</ul>
<p>La mejora del MLP no justifica la opacidad.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="la-optimizacion-como-dialogo-con-el-dominio" class="slide level2">
<h2>La optimizacion como dialogo con el dominio</h2>
<p>Caso de desercion estudiantil con restriccion de recursos:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>C</th>
<th>Recall</th>
<th>Precision</th>
<th>F1</th>
<th>N predichos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.01</td>
<td>0.62</td>
<td>0.71</td>
<td>0.66</td>
<td>98</td>
</tr>
<tr class="even">
<td>0.1</td>
<td>0.74</td>
<td>0.65</td>
<td>0.69</td>
<td>127</td>
</tr>
<tr class="odd">
<td><strong>1.0</strong></td>
<td><strong>0.81</strong></td>
<td><strong>0.58</strong></td>
<td><strong>0.68</strong></td>
<td><strong>156</strong></td>
</tr>
<tr class="even">
<td>10.0</td>
<td>0.83</td>
<td>0.54</td>
<td>0.65</td>
<td>172</td>
</tr>
<tr class="odd">
<td>100.0</td>
<td>0.84</td>
<td>0.52</td>
<td>0.64</td>
<td>181</td>
</tr>
</tbody>
</table>
</section>
<section id="la-optimizacion-como-dialogo-con-el-dominio-1" class="slide level2">
<h2>La optimizacion como dialogo con el dominio</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>La decision no es matematica, es de negocio</strong></p>
</div>
<div class="callout-content">
<p>Contexto: el sistema puede intervenir con 150 estudiantes por semestre.</p>
<ul>
<li>C = 100: recall maximo, pero 181 predicciones — excede capacidad.</li>
<li>C = 1: recall 0.81, 156 predicciones — ligeramente sobre capacidad, negociable.</li>
<li>C = 0.1: 127 predicciones, recall aceptable 0.74.</li>
</ul>
<p><strong>Recomendacion:</strong> C = 1. Argumento: captura 81% de estudiantes en riesgo con una carga ligeramente superior a 150. El equipo puede considerar ampliar capacidad levemente.</p>
<p>Grid Search y Random Search generan las opciones. La decision final requiere dialogo con el stakeholder.</p>
</div>
</div>
</div>
</section>
<section id="analisis-de-errores" class="slide level2">
<h2>Analisis de errores</h2>
<p>Se genera <code>outputs/errors/errors.csv</code> con:</p>
<ul>
<li>features de la muestra,</li>
<li>etiqueta real,</li>
<li>prediccion,</li>
<li>probabilidades,</li>
<li>tipo de error (FP/FN de maligno).</li>
</ul>
<div class="columns">
<div class="column" style="width:55%;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href=""></a><span class="co"># Como se genera (en evaluate.py)</span></span>
<span id="cb12-2"><a href=""></a>errors <span class="op">=</span> pd.DataFrame(X_test, columns<span class="op">=</span>feature_names)</span>
<span id="cb12-3"><a href=""></a>errors[<span class="st">"y_true"</span>]    <span class="op">=</span> y_test</span>
<span id="cb12-4"><a href=""></a>errors[<span class="st">"y_pred"</span>]    <span class="op">=</span> preds</span>
<span id="cb12-5"><a href=""></a>errors[<span class="st">"p_maligno"</span>] <span class="op">=</span> proba[:, <span class="dv">0</span>]</span>
<span id="cb12-6"><a href=""></a>errors[<span class="st">"error_type"</span>] <span class="op">=</span> errors.<span class="bu">apply</span>(</span>
<span id="cb12-7"><a href=""></a>    <span class="kw">lambda</span> r: <span class="st">"FN_maligno"</span> <span class="cf">if</span> r.y_true<span class="op">==</span><span class="dv">0</span> <span class="kw">and</span> r.y_pred<span class="op">==</span><span class="dv">1</span></span>
<span id="cb12-8"><a href=""></a>    <span class="cf">else</span> <span class="st">"FP_maligno"</span> <span class="cf">if</span> r.y_true<span class="op">==</span><span class="dv">1</span> <span class="kw">and</span> r.y_pred<span class="op">==</span><span class="dv">0</span></span>
<span id="cb12-9"><a href=""></a>    <span class="cf">else</span> <span class="st">"OK"</span>, axis<span class="op">=</span><span class="dv">1</span></span>
<span id="cb12-10"><a href=""></a>)</span>
<span id="cb12-11"><a href=""></a>errors[errors.error_type <span class="op">!=</span> <span class="st">"OK"</span>].to_csv(</span>
<span id="cb12-12"><a href=""></a>    <span class="st">"outputs/errors/errors.csv"</span>, index<span class="op">=</span><span class="va">False</span></span>
<span id="cb12-13"><a href=""></a>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column" style="width:45%;">
<p><strong>Preguntas al revisar el CSV:</strong></p>
<ul>
<li>Los FN (malignos perdidos): tienen features atipicas?</li>
<li>Tienen <code>p_maligno</code> muy cerca de 0.5? (casos ambiguos)</li>
<li>Son los mismos casos con todas las seeds? (error sistematico vs estocastico)</li>
</ul>
<p>Si los mismos casos fallan con Logistic y MLP, el error es del dato, no del modelo.</p>
</div></div>
</section>
<section id="lectura-practica-de-errors.csv" class="slide level2">
<h2>Lectura practica de errors.csv</h2>
<pre><code>radius_mean  texture_mean  ...  y_true  y_pred  p_maligno  error_type
    12.3          18.2     ...    0       1       0.43      FN_maligno
    11.8          17.6     ...    0       1       0.48      FN_maligno
    13.1          22.4     ...    0       1       0.46      FN_maligno</code></pre>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Patron a buscar</strong></p>
</div>
<div class="callout-content">
<p>Si los FN tienen <code>p_maligno</code> entre 0.40 y 0.50 con threshold = 0.50, son casos que el modelo considera ambiguos. La solucion puede ser bajar el threshold, no cambiar el modelo.</p>
<p>Si los FN tienen <code>p_maligno</code> &lt; 0.30, el modelo esta muy equivocado en esas muestras. Hay que investigar las features de esos casos especificos.</p>
<p>Un punto puede ser influyente (cambiar los coeficientes si se elimina) sin tener un error grande, o tener un error grande sin ser influyente. Ambos merecen investigacion.</p>
</div>
</div>
</div>
</section>
<section id="diagnosticos-brecha-train-vs-test" class="slide level2">
<h2>Diagnosticos: brecha train vs test</h2>
<p>Un buen modelo tiene metricas similares en train y test. Una brecha grande indica overfitting.</p>
<div id="cell-train-test-gap" class="cell" data-fig-height="3.8" data-fig-width="9" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="dia3_slides_files/figure-revealjs/train-test-gap-output-1.png" id="train-test-gap" width="1154" height="374"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Lectura del diagnostico</strong></p>
</div>
<div class="callout-content">
<p>Todas las brechas son menores a 0.05 — el modelo <strong>no muestra signos de overfitting severo</strong>.</p>
<ul>
<li>accuracy gap = 0.034: normal para este tamano de dataset</li>
<li>recall gap = 0.009: el modelo generaliza bien el recall</li>
<li>AUC gap = 0.004: discriminacion consistente entre train y test</li>
</ul>
<p>Conclusion: el modelo aprendio patrones reales, no ruido de los datos de entrenamiento.</p>
</div>
</div>
</div>
</section>
<section class="slide level2">

</section>
<section>
<section id="interpretacion-de-los-coeficientes-reales-del-modelo" class="title-slide slide level1 center">
<h1>Interpretacion de los coeficientes reales del modelo</h1>

</section>
<section id="interpretacion-coeficientes-reales-del-modelo" class="slide level2">
<h2>Interpretacion — coeficientes reales del modelo</h2>
<div id="cell-coefficients" class="cell" data-fig-height="4.4" data-fig-width="9" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="dia3_slides_files/figure-revealjs/coefficients-output-1.png" id="coefficients" width="1151" height="374"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Lectura de los coeficientes reales</strong></p>
</div>
<div class="callout-content">
<p>Los 3 features mas influyentes son <strong>radius error</strong>, <strong>worst texture</strong> y <strong>worst concave points</strong> — todos con coeficiente negativo: mayor valor del feature → mayor probabilidad de maligno (clase 0).</p>
<p>Esto es consistente con el conocimiento medico: tumores malignos son mas grandes, mas irregulares y con mayor variabilidad de forma. El modelo aprendio los patrones correctos.</p>
<p><strong>MLP:</strong> sin coeficientes interpretables. Si MLP y Logistic fallan en los mismos casos, el problema es del dato, no del modelo.</p>
</div>
</div>
</div>
</section>
<section id="top-features-de-logistic-por-que-importan" class="slide level2">
<h2>Top features de Logistic — por que importan</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Coef.</th>
<th>Significado clinico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>radius error</code></td>
<td>-1.115</td>
<td>variabilidad del radio → tumor irregular</td>
</tr>
<tr class="even">
<td><code>worst texture</code></td>
<td>-1.108</td>
<td>textura maxima → tejido rugoso maligno</td>
</tr>
<tr class="odd">
<td><code>worst concave points</code></td>
<td>-1.029</td>
<td>concavidades extremas → forma irregular</td>
</tr>
<tr class="even">
<td><code>worst radius</code></td>
<td>-0.994</td>
<td>radio maximo → tumor grande</td>
</tr>
<tr class="odd">
<td><code>worst area</code></td>
<td>-0.986</td>
<td>area maxima → correlaciona con tamano</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Conexion con conocimiento medico</strong></p>
</div>
<div class="callout-content">
<p>Los features de morfologia (perimetro, concavidades, radio) son exactamente lo que un radiologo evalua visualmente. El modelo aprendio patrones consistentes con la literatura medica — eso refuerza la confianza en el resultado.</p>
<p>Del PDF: los diagnosticos son preguntas, no sentencias. Si un coeficiente tiene signo inesperado, investigar antes de reportar — puede ser multicolinealidad, no un error del modelo.</p>
</div>
</div>
</div>
</section>
<section id="discusion" class="slide level2">
<h2>Discusion</h2>
<p><strong>¿Mas complejo = mejor?</strong></p>
<p>No necesariamente.</p>
<p>Decidimos por evidencia conjunta:</p>
<ul>
<li>desempeno en test,</li>
<li>estabilidad entre seeds,</li>
<li>sensibilidad a threshold,</li>
<li>capacidad de explicacion.</li>
</ul>
</section>
<section id="discusion-1" class="slide level2">
<h2>Discusion</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p><strong>Marco de decision:</strong></p>
<p>Si MLP mejora recall &gt; 0.03 de forma estable (std &lt; 0.01 entre seeds) y la mejora se sostiene en analisis de errores: → usar MLP, documentar limitaciones</p>
<p>Si la mejora es &lt; 0.03 o inestable: → usar Logistic, documentar robustez y explicabilidad</p>
</div><div class="column" style="width:47%;">
<p><strong>Preguntas guia:</strong></p>
<ol type="1">
<li><p>Si MLP sube accuracy pero baja recall maligno, es mejor o peor?</p></li>
<li><p>Si cambia mucho entre seeds, confiarias en el resultado reportado?</p></li>
<li><p>Si MLP mejora poco y pierde interpretabilidad, vale la pena el costo?</p></li>
<li><p>Que error es mas critico aqui: FP o FN de maligno?</p></li>
</ol>
</div></div>
</section>
<section id="el-circulo-completo-de-la-evaluacion" class="slide level2">
<h2>El circulo completo de la evaluacion</h2>
<p>El proceso es iterativo, no lineal:</p>
<div class="cell" data-reveal="true" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["Problema\ny metricas"] --&gt; B["Grid / Random\nSearch + CV"]
    B --&gt; C["Seleccion\nde modelo"]
    C --&gt; D["Diagnosticos\nde residuales"]
    D --&gt; E{"Patrones\nen errores?"}
    E --&gt;|Si| F["Mejorar\nespecificacion"]
    F --&gt; B
    E --&gt;|No| G["AIC / BIC\nvalidacion teorica"]
    G --&gt; H{"CV y AIC/BIC\ncoinciden?"}
    H --&gt;|Si| I["Evidencia\nrobusta"]
    H --&gt;|No| F
    I --&gt; J["Evaluar UNA\nVEZ en test"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>La seleccion de modelos no es una receta con pasos fijos</strong></p>
</div>
<div class="callout-content">
<p>Es una decision de diseño que requiere entender el problema, conocer las herramientas, saber interpretar los resultados y reconocer las limitaciones. No hay respuestas universales. Hay principios que guian las decisiones.</p>
</div>
</div>
</div>
</section>
<section id="conexion-con-modelos-modernos" class="slide level2">
<h2>Conexion con modelos modernos</h2>
<p>A medida que sube complejidad, sube necesidad de validacion fuerte.</p>
<p>Este dia es un puente hacia modelos mas modernos:</p>
<ul>
<li>mayor capacidad,</li>
<li>mayor riesgo de sobreajuste,</li>
<li>menor interpretabilidad directa.</li>
</ul>
<p>La disciplina experimental del pipeline es la defensa principal.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>La escala de complejidad:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Modelo</th>
<th>Params</th>
<th>Interpretable</th>
<th>Necesita seeds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Logistic</td>
<td>~30</td>
<td>si</td>
<td>poco</td>
</tr>
<tr class="even">
<td>MLP (64,32)</td>
<td>~2500</td>
<td>no</td>
<td>mas</td>
</tr>
<tr class="odd">
<td>Random Forest</td>
<td>variable</td>
<td>parcial</td>
<td>mas</td>
</tr>
<tr class="even">
<td>XGBoost</td>
<td>variable</td>
<td>parcial</td>
<td>mas</td>
</tr>
<tr class="odd">
<td>Red profunda</td>
<td>millones</td>
<td>no</td>
<td>critico</td>
</tr>
</tbody>
</table>
<p><strong>Regla:</strong> cuanta mas capacidad, mas validacion necesaria.</p>
</div><div class="column" style="width:50%;">
<p><strong>Lo que hicimos hoy aplica siempre:</strong></p>
<ul>
<li>multiples seeds → valido para cualquier modelo estocastico</li>
<li>Grid / Random Search + CV → necesario antes de cualquier deploy</li>
<li>analisis de errores → obligatorio en dominios clinicos</li>
<li>AIC/BIC → complementa CV con perspectiva teorica</li>
<li>interpretacion → requerida en muchos contextos regulatorios (GDPR, FDA)</li>
</ul>
<p>La herramienta cambia. El rigor experimental no.</p>
</div></div>
</section>
<section id="resumen-ejecutivo-h1-sostenida" class="slide level2">
<h2>Resumen ejecutivo — H1 sostenida</h2>
<div id="cell-h1-summary" class="cell" data-fig-height="3.6" data-fig-width="9" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="dia3_slides_files/figure-revealjs/h1-summary-output-1.png" id="h1-summary" width="1154" height="452"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Decision final argumentada</strong></p>
</div>
<div class="callout-content">
<p>Modelo: <strong>LogisticRegression</strong> (C=1.0, class_weight=balanced, threshold=0.4)</p>
<p>Argumentos: (1) H1 sostenida con evidencia numerica, (2) recall estable entre seeds (std=0.000), (3) coeficientes interpretables coherentes con conocimiento medico, (4) brecha train/test &lt; 0.04 — sin overfitting.</p>
</div>
</div>
</div>
</section>
<section id="cierre" class="slide level2">
<h2>Cierre</h2>
<p>No buscamos el mejor numero aislado.</p>
<p>Buscamos el <strong>modelo mas confiable</strong> para la decision real.</p>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Checklist de salida de Dia 3:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">comparacion Logistic vs MLP completada,</label></li>
<li><label><input type="checkbox">estabilidad documentada (5 seeds, media +/- std),</label></li>
<li><label><input type="checkbox">sensibilidad a hiperparametros registrada (Grid o Random Search),</label></li>
<li><label><input type="checkbox">threshold optimo identificado en validacion,</label></li>
<li><label><input type="checkbox"><code>outputs/errors/errors.csv</code> generado y revisado,</label></li>
<li><label><input type="checkbox">top 5 features de Logistic discutidos,</label></li>
<li><label><input type="checkbox">AIC/BIC calculados y comparados con CV,</label></li>
<li><label><input type="checkbox">decision argumentada: que modelo y por que.</label></li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>El entregable del dia</strong></p>
</div>
<div class="callout-content">
<p>No es el modelo con mayor recall.</p>
<p>Es el <strong>argumento</strong> que justifica por que ese modelo es el correcto para este problema:</p>
<ul>
<li>metrica primaria cumplida (recall &gt;= 0.90),</li>
<li>resultado estable bajo variacion,</li>
<li>errores criticos conocidos y documentados,</li>
<li>explicacion coherente con el dominio,</li>
<li>limitaciones reconocidas explicitamente.</li>
</ul>
</div>
</div>
</div>
</div></div>
</section>
<section id="discusion-final-produccion" class="slide level2">
<h2>Discusion final (produccion)</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Ejemplos de monitoreo:</strong></p>
<ul>
<li>drift de distribucion de features (cambia la poblacion de pacientes?)</li>
<li>caida de recall en maligno mes a mes</li>
<li>cambio en tasa de falsos negativos por cohorte</li>
<li>estabilidad de threshold recomendado</li>
<li>tiempo de inferencia si el modelo escala</li>
</ul>
<p><strong>Herramienta:</strong> W&amp;B Monitoring o Evidently AI para deteccion de drift.</p>
</div><div class="column" style="width:45%;">
<p><strong>Lo que faltaria antes de produccion:</strong></p>
<ol type="1">
<li>Validacion externa (otro hospital, otra cohorte)</li>
<li>Evaluacion de equidad (funciona igual en todos los subgrupos demograficos?)</li>
<li>Auditoria de datos (quien recopilo las muestras? como?)</li>
<li>Revision etica y regulatoria</li>
<li>Plan de rollback si el recall cae por debajo de 0.90</li>
</ol>
</div></div>
<p>Ninguno de estos pasos invalida el trabajo de hoy. Los complementa.</p>
<p>No es suficiente reportar “mejor modelo: C = 1”. Hay que explicar que configuraciones evaluaron, que trade-offs encontraron, como se conecta con las prioridades del stakeholder, y que limitaciones reconocen.</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="Logo_FC_Color.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>Sesión 3 · Workshop ML · Clasificador de cáncer de mama · CPU</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="dia3_slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="dia3_slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="dia3_slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="dia3_slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="dia3_slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="dia3_slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="dia3_slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="dia3_slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="dia3_slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="dia3_slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>